### ISSUE TITLE
Candidate Recommendation tracking issue

### ISSUE THREAD

**Issue by chrisn** [w3c/webcodecs#784]
This issue tracks the issues needed to prepare the WebCodecs API for publication as Candidate Recommendation.

Open issues:

- [ ] See [CR Blocking issues](https://github.com/w3c/webcodecs/issues?q=is%3Aissue+is%3Aopen+label%3A%22CR+Blocking%22)

Horizontal reviews and self-reviews:

- [ ] TAG review: see https://github.com/w3ctag/design-reviews/issues/433 and https://github.com/w3ctag/design-reviews/issues/612
- [ ] Accessibility review
- [ ] Internationalization self review: See [checklist](https://www.w3.org/International/i18n-drafts/techniques/shortchecklist)
- [ ] Internationalization review
- [ ] Privacy [self review](https://github.com/w3c/webcodecs/blob/main/security-privacy-questionnaire.md)
- [ ] Privacy review: see [open issues](https://github.com/w3c/webcodecs/labels/privacy-needs-resolution) and [PING tracking issues](https://github.com/w3cping/tracking-issues/issues?q=is%3Aissue+webcodecs)
- [ ] Security: see https://github.com/w3c/security-request/issues/1
